In [1]:
from blg_strain.utils.saver import Saver

In [2]:
s = Saver()

In [3]:
s.a = 1

In [4]:
s.save(r'E:\sBLG_data\saver.npz')

In [5]:
s2 = s.load(r'E:\sBLG_data\saver.npz')

In [6]:
s2.a

1

In [7]:
from blg_strain.utils.saver import Saver
import numpy as np
import h5py

In [8]:
a = np.linspace(0,2)

In [9]:
data_dict = {'a': a, 'b': a**2, 'c':3}

In [10]:
with h5py.File(r'E:\sBLG_data\test.h5', 'w') as f:
    for k, v in data_dict.items():
        f.create_dataset(k, data=v)

In [11]:
new_dict = {}
with h5py.File(r'E:\sBLG_data\test.h5', 'r') as f:
    new_dict = {k: v[()] for k, v in f.items()} # [()] gets the value

In [12]:
new_dict

{'a': array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
        0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
        0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
        0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
        0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
        1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
        1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
        1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
        1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
        1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ]),
 'b': array([0.00000000e+00, 1.66597251e-03, 6.66389005e-03, 1.49937526e-02,
        2.66555602e-02, 4.16493128e-02, 5.99750104e-02, 8.16326531e-02,
        1.06622241e-01, 1.34943773e-01, 1.66597251e-01, 2.01582674e-01,
        2.39900042e-01, 2.81549354e-01, 3.26530612e-01, 3.74843815e-01,
        4.26488963e-

In [13]:
from blg_strain.utils.saver import Saver

In [14]:
import numpy as np
import h5py

In [15]:
s = Saver()

In [16]:
s.a = np.linspace(0,2)
s.b = np.meshgrid(s.a, s.a)
s.c = 3
s.d = 'Four'

In [17]:
s.save('test.h5')

In [18]:
s2 = s.load('test.h5')

In [19]:
s2.__dict__

{'a': array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
        0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
        0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
        0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
        0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
        1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
        1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
        1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
        1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
        1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ]),
 'b': array([[[0.        , 0.04081633, 0.08163265, ..., 1.91836735,
          1.95918367, 2.        ],
         [0.        , 0.04081633, 0.08163265, ..., 1.91836735,
          1.95918367, 2.        ],
         [0.        , 0.04081633, 0.08163265, ..., 1.91836735,
          1.95918367, 2.        ],
         ...,


# Savers within savers

In [1]:
from blg_strain.utils.saver import Saver
import numpy as np
import h5py

In [2]:
s = Saver()
s.s = Saver()
s.s.s = Saver()

In [3]:
s.a = np.linspace(0,1, 10)
s.s.a = np.linspace(-1,0, 10)


In [4]:
s.save('test.h5')

In [5]:
s2 = s.load('test.h5')

In [6]:
s2.__dict__

{'a': array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 's': <blg_strain.utils.saver.Saver at 0x1bdfabb4788>}

In [8]:
s2.s.__dict__

{'a': array([-1.        , -0.88888889, -0.77777778, -0.66666667, -0.55555556,
        -0.44444444, -0.33333333, -0.22222222, -0.11111111,  0.        ]),
 's': <blg_strain.utils.saver.Saver at 0x1bdff4dca08>}

In [10]:
s2.s.s.__dict__

{}

# Subclass

In [1]:
from blg_strain.utils.saver import Saver
from blg_strain.bands import Valley
import numpy as np
import h5py

In [2]:
s = Saver()

In [3]:
s.s = Valley()

In [4]:
s.save('test.h5')

In [5]:
s2 = Saver.load('test.h5')

In [6]:
s2.__dict__

{'s': <blg_strain.bands.Valley at 0x284e42ada08>}

In [7]:
s2.s.__dict__

{'sl': <blg_strain.utils.saver.Saver at 0x284e4a700c8>,
 'window': 0.1,
 'Delta': 0,
 'valley': 'K'}

In [8]:
s2.s.sl.__dict__

{}

# Try the full nested structure

In [1]:
from blg_strain.lattice import StrainedLattice
from blg_strain.bands import BandStructure, FilledBands

In [2]:
sl = StrainedLattice(0.01, 0)

In [3]:
bs = BandStructure(sl, Delta=0.01)

In [4]:
fb = FilledBands(bs, EF=0.006, T=0)

In [5]:
fb.save('test.h5')

In [6]:
fb2 = FilledBands.load('test.h5')

In [7]:
fb2.bs.K.sl.__dict__

{'eps': 0.01, 'theta': 0, 'strain': array([[ 0.01   ,  0.     ],
        [ 0.     , -0.00165]]), 'deltas': array([[ 0.        ,  0.99835   ],
        [ 0.87468566, -0.499175  ],
        [-0.87468566, -0.499175  ]]), 'deltans': array([[ 1.74937132,  0.        ],
        [-1.74937132,  0.        ],
        [ 0.87468566,  1.497525  ],
        [ 0.87468566, -1.497525  ],
        [-0.87468566,  1.497525  ],
        [-0.87468566, -1.497525  ]]), 'gamma0s': array([3.17568078, 3.09340252, 3.09340252]), 'gamma3s': array([0.38062752, 0.3773115 , 0.3773115 ]), 'gamma4s': array([0.14023119, 0.1390095 , 0.1390095 ]), 'gammans': array([0.31284   , 0.31284   , 0.31435674, 0.31435674, 0.31435674,
        0.31435674]), 'dimer': 0.022, '_kxa': array([-2.90207898, -2.87291236, -2.84374574, -2.81457911, -2.78541249,
        -2.75624587, -2.72707925, -2.69791262, -2.668746  , -2.63957938,
        -2.61041275, -2.58124613, -2.55207951, -2.52291288, -2.49374626,
        -2.46457964, -2.43541302, -2.40624639,

In [8]:
import numpy as np

In [9]:
np.savez_compressed('test.npz', **fb.__dict__)

In [10]:
obj = FilledBands()

In [11]:
data = np.load('test.npz', allow_pickle=True)

In [12]:
for attr in data.files:
    setattr(obj, attr, data[attr].item())

In [19]:
obj.bs.K.sl.__dict__

{'eps': 0.01, 'theta': 0, 'strain': array([[ 0.01   ,  0.     ],
        [ 0.     , -0.00165]]), 'deltas': [array([0.     , 0.99835]),
  array([ 0.87468566, -0.499175  ]),
  array([-0.87468566, -0.499175  ])], 'deltans': [array([1.74937132, 0.        ]),
  array([-1.74937132,  0.        ]),
  array([0.87468566, 1.497525  ]),
  array([ 0.87468566, -1.497525  ]),
  array([-0.87468566,  1.497525  ]),
  array([-0.87468566, -1.497525  ])], 'gamma0s': [3.175680777907145,
  3.0934025208166527,
  3.0934025208166527], 'gamma3s': [0.38062751755961866,
  0.37731150457745305,
  0.37731150457745305], 'gamma4s': [0.1402311906798595,
  0.1390095016864301,
  0.1390095016864301], 'gammans': [0.31284000000000006,
  0.31284000000000006,
  0.3143567430298338,
  0.3143567430298338,
  0.3143567430298338,
  0.3143567430298338], 'dimer': 0.022, '_kxa': array([-2.90207898, -2.87291236, -2.84374574, -2.81457911, -2.78541249,
        -2.75624587, -2.72707925, -2.69791262, -2.668746  , -2.63957938,
        -2.610

# Check file size npz versus h5

In [1]:
from blg_strain.lattice import StrainedLattice
from blg_strain.bands import BandStructure, FilledBands

In [2]:
sl = StrainedLattice(0.01, 0.1)

In [3]:
bs = BandStructure(sl, Delta=0.01)
bs.calculate(500,500)

In [4]:
fb = FilledBands(bs)

In [5]:
fb.calculate()

In [6]:
%%time
fb.save('test.npz')

Wall time: 12.1 s


In [7]:
%%time
fb.save_hdf5('test.h5')

Wall time: 2.36 s


In [8]:
%%time
fb.save_hdf5('testc.h5', compression=9)

Wall time: 16.2 s


In [9]:
%%time
fb2 = FilledBands.load('test.npz')

Wall time: 2.61 s


In [12]:
%%time
fb2 = FilledBands.load_hdf5('test.h5')

Wall time: 1.77 s


In [13]:
%%time
fb2 = FilledBands.load_hdf5('testc.h5')

Wall time: 3.1 s


# Now don't save classes shared commonly
(e.g. don't save StrainedLattice multiple times). Other than the object being saved, the only subobjects we want to save will be `Valley` objects

In [1]:
from blg_strain.lattice import StrainedLattice
from blg_strain.bands import BandStructure, FilledBands

In [2]:
sl = StrainedLattice(0.01, 0.1)

In [3]:
bs = BandStructure(sl, Delta=0.01)
bs.calculate(500,500)

In [4]:
fb = FilledBands(bs)

In [5]:
fb.calculate()

In [6]:
%time sl.save(r'E:\sBLG_data\testsl.npz')
%time bs.save(r'E:\sBLG_data\testbs.npz')
%time fb.save(r'E:\sBLG_data\testfb.npz')

Wall time: 41 ms
Wall time: 408 ms


TypeError: save() takes 1 positional argument but 2 were given

In [6]:
%time sl.save_hdf5(r'E:\sBLG_data\testsl.h5')
%time bs.save_hdf5(r'E:\sBLG_data\testbs.h5')
%time fb.save_hdf5(r'E:\sBLG_data\testfb.h5')

Wall time: 50 ms
Wall time: 461 ms
Wall time: 24 ms


In [8]:
%time sl.save_hdf5(r'E:\sBLG_data\testslc.h5', compression=1)
%time bs.save_hdf5(r'E:\sBLG_data\testbsc.h5', compression=1)
%time fb.save_hdf5(r'E:\sBLG_data\testfbc.h5', compression=1)

Wall time: 490 ms
Wall time: 4.5 s
Wall time: 72.7 ms


In [14]:
%time sl2 = BandStructure.load(r'E:\sBLG_data\testsl.npz')
%time bs2 = BandStructure.load(r'E:\sBLG_data\testbs.npz')
%time fb2 = FilledBands.load(r'E:\sBLG_data\testfb.npz')

Wall time: 94.9 ms
Wall time: 1.17 s
Wall time: 59 ms


In [15]:
%time sl2 = BandStructure.load_hdf5(r'E:\sBLG_data\testsl.h5')
%time bs2 = BandStructure.load_hdf5(r'E:\sBLG_data\testbs.h5')
%time fb2 = FilledBands.load_hdf5(r'E:\sBLG_data\testfb.h5')

Wall time: 588 ms
Wall time: 113 ms
Wall time: 22 ms


In [16]:
%time sl2 = BandStructure.load_hdf5(r'E:\sBLG_data\testslc.h5')
%time bs2 = BandStructure.load_hdf5(r'E:\sBLG_data\testbsc.h5')
%time fb2 = FilledBands.load_hdf5(r'E:\sBLG_data\testfbc.h5')

Wall time: 746 ms
Wall time: 791 ms
Wall time: 65 ms


In [11]:
import numpy as np

In [6]:
for k, v in bs.K.__dict__.items():
    try:
        print(k, v.nbytes, v.dtype)
    except:
        pass

kxa 4000 float64
kya 4000 float64
Kxa 2000000 float64
Kya 2000000 float64
E 8000000 float64
Psi 32000000 complex64
Omega 8000000 float64
Mu 8000000 float64
splE 32 object
splPr 128 object
splPi 128 object
splO 32 object
splM 32 object


In [10]:
bs.K.Psi.shape

(4, 4, 500, 500)

# Compress only feq arrays in FilledBands

In [1]:
from blg_strain.lattice import StrainedLattice
from blg_strain.bands import BandStructure, FilledBands

In [2]:
sl = StrainedLattice(0.01, 0.1)
sl.calculate()

In [4]:
bs = BandStructure(sl, Delta=0.01)
bs.calculate(500,500)

In [5]:
fb = FilledBands(bs)

In [6]:
fb.calculate()

In [7]:
%time sl.save(r'E:\sBLG_data\testsl.h5')
%time bs.save(r'E:\sBLG_data\testbs.h5')
%time fb.save(r'E:\sBLG_data\testfb.h5')

Wall time: 36 ms
Wall time: 536 ms
Wall time: 138 ms


In [8]:
%time sl2 = sl.load(r'E:\sBLG_data\testsl.h5')
%time bs2 = bs.load(r'E:\sBLG_data\testbs.h5')
%time fb2 = fb.load(r'E:\sBLG_data\testfb.h5')

Wall time: 13 ms
Wall time: 91.9 ms
Wall time: 41 ms


In [9]:
sl.__dict__

{'eps': 0.01, 'theta': 0.1, 'strain': array([[ 0.00988389,  0.00115725],
        [ 0.00115725, -0.00153389]]), 'deltas': array([[ 0.00115725,  0.99846611],
        [ 0.87400648, -0.49823085],
        [-0.87516373, -0.50023526]]), 'gamma0s': array([3.17456838, 3.10323415, 3.08468245]), 'gamma3s': array([0.38058307, 0.37771081, 0.37695663]), 'gamma4s': array([0.14021482, 0.13915662, 0.13887876]), 'deltans': array([[ 1.7491702 ,  0.00200441],
        [-1.7491702 , -0.00200441],
        [ 0.87632097,  1.49870138],
        [ 0.87284923, -1.49669696],
        [-0.87284923,  1.49669696],
        [-0.87632097, -1.49870138]]), 'gammans': array([0.31285536, 0.31285536, 0.31410677, 0.31461686, 0.31461686,
        0.31410677]), 'dimer': 0.022, 'K_bz': array([ 2.40850046, -0.00551965]), 'Kp_bz': array([-2.40850046,  0.00551965]), 'K': array([ 2.41151163, -0.00667818]), 'Kp': array([-2.41151163,  0.00667818]), 'bz': [array([ 2.40850046, -0.00551965]),
  array([ 1.18600288, -2.09625908]),
  array([-1

In [10]:
sl2.__dict__

{'eps': 0.01, 'theta': 0.1, 'strain': array([[ 0.00988389,  0.00115725],
        [ 0.00115725, -0.00153389]]), 'K': array([ 2.41151163, -0.00667818]), 'K_bz': array([ 2.40850046, -0.00551965]), 'Kp': array([-2.41151163,  0.00667818]), 'Kp_bz': array([-2.40850046,  0.00551965]), 'bz': array([[ 2.40850046, -0.00551965],
        [ 1.18600288, -2.09625908],
        [-1.18119547, -2.0989717 ],
        [-2.40850046,  0.00551965],
        [-1.18600288,  2.09625908],
        [ 1.18119547,  2.0989717 ]]), 'deltans': array([[ 1.7491702 ,  0.00200441],
        [-1.7491702 , -0.00200441],
        [ 0.87632097,  1.49870138],
        [ 0.87284923, -1.49669696],
        [-0.87284923,  1.49669696],
        [-0.87632097, -1.49870138]]), 'deltas': array([[ 0.00115725,  0.99846611],
        [ 0.87400648, -0.49823085],
        [-0.87516373, -0.50023526]]), 'dimer': 0.022, 'gamma0s': array([3.17456838, 3.10323415, 3.08468245]), 'gamma3s': array([0.38058307, 0.37771081, 0.37695663]), 'gamma4s': array([0.140