In [1]:
from blg_strain.utils.saver import Saver

In [2]:
s = Saver()

In [3]:
s.a = 1

In [4]:
s.save(r'E:\sBLG_data\saver.npz')

In [5]:
s2 = s.load(r'E:\sBLG_data\saver.npz')

In [6]:
s2.a

1

In [7]:
from blg_strain.utils.saver import Saver
import numpy as np
import h5py

In [8]:
a = np.linspace(0,2)

In [9]:
data_dict = {'a': a, 'b': a**2, 'c':3}

In [10]:
with h5py.File(r'E:\sBLG_data\test.h5', 'w') as f:
    for k, v in data_dict.items():
        f.create_dataset(k, data=v)

In [11]:
new_dict = {}
with h5py.File(r'E:\sBLG_data\test.h5', 'r') as f:
    new_dict = {k: v[()] for k, v in f.items()} # [()] gets the value

In [12]:
new_dict

{'a': array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
        0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
        0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
        0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
        0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
        1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
        1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
        1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
        1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
        1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ]),
 'b': array([0.00000000e+00, 1.66597251e-03, 6.66389005e-03, 1.49937526e-02,
        2.66555602e-02, 4.16493128e-02, 5.99750104e-02, 8.16326531e-02,
        1.06622241e-01, 1.34943773e-01, 1.66597251e-01, 2.01582674e-01,
        2.39900042e-01, 2.81549354e-01, 3.26530612e-01, 3.74843815e-01,
        4.26488963e-

In [13]:
from blg_strain.utils.saver import Saver

In [14]:
import numpy as np
import h5py

In [15]:
s = Saver()

In [16]:
s.a = np.linspace(0,2)
s.b = np.meshgrid(s.a, s.a)
s.c = 3
s.d = 'Four'

In [17]:
s.save('test.h5')

In [18]:
s2 = s.load('test.h5')

In [19]:
s2.__dict__

{'a': array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
        0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
        0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
        0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
        0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
        1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
        1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
        1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
        1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
        1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ]),
 'b': array([[[0.        , 0.04081633, 0.08163265, ..., 1.91836735,
          1.95918367, 2.        ],
         [0.        , 0.04081633, 0.08163265, ..., 1.91836735,
          1.95918367, 2.        ],
         [0.        , 0.04081633, 0.08163265, ..., 1.91836735,
          1.95918367, 2.        ],
         ...,


# Savers within savers

In [1]:
from blg_strain.utils.saver import Saver
import numpy as np
import h5py

In [2]:
s = Saver()
s.s = Saver()
s.s.s = Saver()

In [3]:
s.a = np.linspace(0,1, 10)
s.s.a = np.linspace(-1,0, 10)


In [4]:
s.save('test.h5')

In [5]:
s2 = s.load('test.h5')

In [6]:
s2.__dict__

{'a': array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 's': <blg_strain.utils.saver.Saver at 0x1bdfabb4788>}

In [8]:
s2.s.__dict__

{'a': array([-1.        , -0.88888889, -0.77777778, -0.66666667, -0.55555556,
        -0.44444444, -0.33333333, -0.22222222, -0.11111111,  0.        ]),
 's': <blg_strain.utils.saver.Saver at 0x1bdff4dca08>}

In [10]:
s2.s.s.__dict__

{}

# Subclass

In [1]:
from blg_strain.utils.saver import Saver
from blg_strain.bands import Valley
import numpy as np
import h5py

In [2]:
s = Saver()

In [3]:
s.s = Valley()

In [4]:
s.save('test.h5')

In [5]:
s2 = Saver.load('test.h5')

In [6]:
s2.__dict__

{'s': <blg_strain.bands.Valley at 0x284e42ada08>}

In [7]:
s2.s.__dict__

{'sl': <blg_strain.utils.saver.Saver at 0x284e4a700c8>,
 'window': 0.1,
 'Delta': 0,
 'valley': 'K'}

In [8]:
s2.s.sl.__dict__

{}

# Try the full nested structure

In [1]:
from blg_strain.lattice import StrainedLattice
from blg_strain.bands import BandStructure, FilledBands

In [2]:
sl = StrainedLattice(0.01, 0)

In [3]:
bs = BandStructure(sl, Delta=0.01)

In [4]:
fb = FilledBands(bs, EF=0.006, T=0)

In [5]:
fb.save('test.h5')

In [6]:
fb2 = FilledBands.load('test.h5')

In [7]:
fb2.bs.K.sl.__dict__

{'eps': 0.01, 'theta': 0, 'strain': array([[ 0.01   ,  0.     ],
        [ 0.     , -0.00165]]), 'deltas': array([[ 0.        ,  0.99835   ],
        [ 0.87468566, -0.499175  ],
        [-0.87468566, -0.499175  ]]), 'deltans': array([[ 1.74937132,  0.        ],
        [-1.74937132,  0.        ],
        [ 0.87468566,  1.497525  ],
        [ 0.87468566, -1.497525  ],
        [-0.87468566,  1.497525  ],
        [-0.87468566, -1.497525  ]]), 'gamma0s': array([3.17568078, 3.09340252, 3.09340252]), 'gamma3s': array([0.38062752, 0.3773115 , 0.3773115 ]), 'gamma4s': array([0.14023119, 0.1390095 , 0.1390095 ]), 'gammans': array([0.31284   , 0.31284   , 0.31435674, 0.31435674, 0.31435674,
        0.31435674]), 'dimer': 0.022, '_kxa': array([-2.90207898, -2.87291236, -2.84374574, -2.81457911, -2.78541249,
        -2.75624587, -2.72707925, -2.69791262, -2.668746  , -2.63957938,
        -2.61041275, -2.58124613, -2.55207951, -2.52291288, -2.49374626,
        -2.46457964, -2.43541302, -2.40624639,

In [8]:
import numpy as np

In [9]:
np.savez_compressed('test.npz', **fb.__dict__)

In [10]:
obj = FilledBands()

In [11]:
data = np.load('test.npz', allow_pickle=True)

In [12]:
for attr in data.files:
    setattr(obj, attr, data[attr].item())

In [19]:
obj.bs.K.sl.__dict__

{'eps': 0.01, 'theta': 0, 'strain': array([[ 0.01   ,  0.     ],
        [ 0.     , -0.00165]]), 'deltas': [array([0.     , 0.99835]),
  array([ 0.87468566, -0.499175  ]),
  array([-0.87468566, -0.499175  ])], 'deltans': [array([1.74937132, 0.        ]),
  array([-1.74937132,  0.        ]),
  array([0.87468566, 1.497525  ]),
  array([ 0.87468566, -1.497525  ]),
  array([-0.87468566,  1.497525  ]),
  array([-0.87468566, -1.497525  ])], 'gamma0s': [3.175680777907145,
  3.0934025208166527,
  3.0934025208166527], 'gamma3s': [0.38062751755961866,
  0.37731150457745305,
  0.37731150457745305], 'gamma4s': [0.1402311906798595,
  0.1390095016864301,
  0.1390095016864301], 'gammans': [0.31284000000000006,
  0.31284000000000006,
  0.3143567430298338,
  0.3143567430298338,
  0.3143567430298338,
  0.3143567430298338], 'dimer': 0.022, '_kxa': array([-2.90207898, -2.87291236, -2.84374574, -2.81457911, -2.78541249,
        -2.75624587, -2.72707925, -2.69791262, -2.668746  , -2.63957938,
        -2.610

# Check file size npz versus h5

In [1]:
from blg_strain.lattice import StrainedLattice
from blg_strain.bands import BandStructure, FilledBands

In [2]:
sl = StrainedLattice(0.01, 0.1)

In [3]:
bs = BandStructure(sl, Delta=0.01)
bs.calculate(2000,2000)

In [4]:
fb = FilledBands(bs)

In [5]:
fb.calculate()

In [6]:
bs.K.sl.__dict__

{'eps': 0.01, 'theta': 0.1, 'strain': array([[ 0.00988389,  0.00115725],
        [ 0.00115725, -0.00153389]]), 'deltas': [array([0.00115725, 0.99846611]),
  array([ 0.87400648, -0.49823085]),
  array([-0.87516373, -0.50023526])], 'deltans': [array([1.7491702 , 0.00200441]),
  array([-1.7491702 , -0.00200441]),
  array([0.87632097, 1.49870138]),
  array([ 0.87284923, -1.49669696]),
  array([-0.87284923,  1.49669696]),
  array([-0.87632097, -1.49870138])], 'gamma0s': [3.1745683778648175,
  3.103234148156414,
  3.0846824476523826], 'gamma3s': [0.3805830693982904,
  0.37771081278235663,
  0.37695663316435346], 'gamma4s': [0.14021481504147543,
  0.13915661523560507,
  0.13887875958686707], 'gammans': [0.3128553559915966,
  0.3128553559915966,
  0.31410676514619656,
  0.3146168648696689,
  0.3146168648696689,
  0.31410676514619656], 'dimer': 0.022, '_kxa': array([-2.90207898, -2.87291236, -2.84374574, -2.81457911, -2.78541249,
        -2.75624587, -2.72707925, -2.69791262, -2.668746  , -2.63

In [21]:
bs.K.__dict__

{'window': 0.1,
 'Delta': 0.01,
 'valley': 'K',
 '_kxa': array([2.36151163, 2.36201414, 2.36251665, 2.36301917, 2.36352168,
        2.36402419, 2.3645267 , 2.36502922, 2.36553173, 2.36603424,
        2.36653675, 2.36703927, 2.36754178, 2.36804429, 2.3685468 ,
        2.36904932, 2.36955183, 2.37005434, 2.37055685, 2.37105937,
        2.37156188, 2.37206439, 2.37256691, 2.37306942, 2.37357193,
        2.37407444, 2.37457696, 2.37507947, 2.37558198, 2.37608449,
        2.37658701, 2.37708952, 2.37759203, 2.37809454, 2.37859706,
        2.37909957, 2.37960208, 2.38010459, 2.38060711, 2.38110962,
        2.38161213, 2.38211464, 2.38261716, 2.38311967, 2.38362218,
        2.38412469, 2.38462721, 2.38512972, 2.38563223, 2.38613474,
        2.38663726, 2.38713977, 2.38764228, 2.38814479, 2.38864731,
        2.38914982, 2.38965233, 2.39015484, 2.39065736, 2.39115987,
        2.39166238, 2.3921649 , 2.39266741, 2.39316992, 2.39367243,
        2.39417495, 2.39467746, 2.39517997, 2.39568248, 2.39

In [22]:
bs.save_hdf5('test.h5')

window 0.1
Delta 0.01
K <blg_strain.bands.Valley object at 0x00000171658FE9C8>
window 0.1
Delta 0.01
valley K
_kxa [2.36151163 2.36201414 2.36251665 2.36301917 2.36352168 2.36402419
 2.3645267  2.36502922 2.36553173 2.36603424 2.36653675 2.36703927
 2.36754178 2.36804429 2.3685468  2.36904932 2.36955183 2.37005434
 2.37055685 2.37105937 2.37156188 2.37206439 2.37256691 2.37306942
 2.37357193 2.37407444 2.37457696 2.37507947 2.37558198 2.37608449
 2.37658701 2.37708952 2.37759203 2.37809454 2.37859706 2.37909957
 2.37960208 2.38010459 2.38060711 2.38110962 2.38161213 2.38211464
 2.38261716 2.38311967 2.38362218 2.38412469 2.38462721 2.38512972
 2.38563223 2.38613474 2.38663726 2.38713977 2.38764228 2.38814479
 2.38864731 2.38914982 2.38965233 2.39015484 2.39065736 2.39115987
 2.39166238 2.3921649  2.39266741 2.39316992 2.39367243 2.39417495
 2.39467746 2.39517997 2.39568248 2.396185   2.39668751 2.39719002
 2.39769253 2.39819505 2.39869756 2.39920007 2.39970258 2.4002051
 2.40070761 2.4

TypeError: Object dtype dtype('O') has no native HDF5 equivalent

In [ ]:
fb.save('test.npz')
# fb.save_hdf5('test.h5')

# Now don't save classes shared commonly (e.g. don't save StrainedLattice multiple times)