In [1]:
from blg_strain.utils.saver import Saver

In [2]:
s = Saver()

In [3]:
s.a = 1

In [4]:
s.save(r'E:\sBLG_data\saver.npz')

In [5]:
s2 = s.load(r'E:\sBLG_data\saver.npz')

In [6]:
s2.a

1

In [7]:
from blg_strain.utils.saver import Saver
import numpy as np
import h5py

In [8]:
a = np.linspace(0,2)

In [9]:
data_dict = {'a': a, 'b': a**2, 'c':3}

In [10]:
with h5py.File(r'E:\sBLG_data\test.h5', 'w') as f:
    for k, v in data_dict.items():
        f.create_dataset(k, data=v)

In [11]:
new_dict = {}
with h5py.File(r'E:\sBLG_data\test.h5', 'r') as f:
    new_dict = {k: v[()] for k, v in f.items()} # [()] gets the value

In [12]:
new_dict

{'a': array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
        0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
        0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
        0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
        0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
        1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
        1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
        1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
        1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
        1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ]),
 'b': array([0.00000000e+00, 1.66597251e-03, 6.66389005e-03, 1.49937526e-02,
        2.66555602e-02, 4.16493128e-02, 5.99750104e-02, 8.16326531e-02,
        1.06622241e-01, 1.34943773e-01, 1.66597251e-01, 2.01582674e-01,
        2.39900042e-01, 2.81549354e-01, 3.26530612e-01, 3.74843815e-01,
        4.26488963e-

In [13]:
from blg_strain.utils.saver import Saver

In [14]:
import numpy as np
import h5py

In [15]:
s = Saver()

In [16]:
s.a = np.linspace(0,2)
s.b = np.meshgrid(s.a, s.a)
s.c = 3
s.d = 'Four'

In [17]:
s.save('test.h5')

In [18]:
s2 = s.load('test.h5')

In [19]:
s2.__dict__

{'a': array([0.        , 0.04081633, 0.08163265, 0.12244898, 0.16326531,
        0.20408163, 0.24489796, 0.28571429, 0.32653061, 0.36734694,
        0.40816327, 0.44897959, 0.48979592, 0.53061224, 0.57142857,
        0.6122449 , 0.65306122, 0.69387755, 0.73469388, 0.7755102 ,
        0.81632653, 0.85714286, 0.89795918, 0.93877551, 0.97959184,
        1.02040816, 1.06122449, 1.10204082, 1.14285714, 1.18367347,
        1.2244898 , 1.26530612, 1.30612245, 1.34693878, 1.3877551 ,
        1.42857143, 1.46938776, 1.51020408, 1.55102041, 1.59183673,
        1.63265306, 1.67346939, 1.71428571, 1.75510204, 1.79591837,
        1.83673469, 1.87755102, 1.91836735, 1.95918367, 2.        ]),
 'b': array([[[0.        , 0.04081633, 0.08163265, ..., 1.91836735,
          1.95918367, 2.        ],
         [0.        , 0.04081633, 0.08163265, ..., 1.91836735,
          1.95918367, 2.        ],
         [0.        , 0.04081633, 0.08163265, ..., 1.91836735,
          1.95918367, 2.        ],
         ...,


# Savers within savers

In [1]:
from blg_strain.utils.saver import Saver
import numpy as np
import h5py

In [2]:
s = Saver()
s.s = Saver()
s.s.s = Saver()

In [3]:
s.a = np.linspace(0,1, 10)
s.s.a = np.linspace(-1,0, 10)


In [4]:
s.save('test.h5')

In [5]:
s2 = s.load('test.h5')

In [6]:
s2.__dict__

{'a': array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 's': <blg_strain.utils.saver.Saver at 0x1bdfabb4788>}

In [8]:
s2.s.__dict__

{'a': array([-1.        , -0.88888889, -0.77777778, -0.66666667, -0.55555556,
        -0.44444444, -0.33333333, -0.22222222, -0.11111111,  0.        ]),
 's': <blg_strain.utils.saver.Saver at 0x1bdff4dca08>}

In [10]:
s2.s.s.__dict__

{}

# Subclass

In [1]:
from blg_strain.utils.saver import Saver
from blg_strain.bands import Valley
import numpy as np
import h5py

In [2]:
s = Saver()

In [3]:
s.s = Valley()

In [4]:
s.save('test.h5')

In [5]:
s2 = Saver.load('test.h5')

In [6]:
s2.__dict__

{'s': <blg_strain.bands.Valley at 0x284e42ada08>}

In [7]:
s2.s.__dict__

{'sl': <blg_strain.utils.saver.Saver at 0x284e4a700c8>,
 'window': 0.1,
 'Delta': 0,
 'valley': 'K'}

In [8]:
s2.s.sl.__dict__

{}

# Try the full nested structure

In [1]:
from blg_strain.lattice import StrainedLattice
from blg_strain.bands import BandStructure, FilledBands

In [2]:
sl = StrainedLattice(0.01, 0)

In [3]:
bs = BandStructure(sl, Delta=0.01)

In [4]:
fb = FilledBands(bs, EF=0.006, T=0)

In [5]:
fb.save('test.h5')

In [6]:
fb2 = FilledBands.load('test.h5')

In [7]:
fb2.bs.K.sl.__dict__

{'eps': 0.01, 'theta': 0, 'strain': array([[ 0.01   ,  0.     ],
        [ 0.     , -0.00165]]), 'deltas': array([[ 0.        ,  0.99835   ],
        [ 0.87468566, -0.499175  ],
        [-0.87468566, -0.499175  ]]), 'deltans': array([[ 1.74937132,  0.        ],
        [-1.74937132,  0.        ],
        [ 0.87468566,  1.497525  ],
        [ 0.87468566, -1.497525  ],
        [-0.87468566,  1.497525  ],
        [-0.87468566, -1.497525  ]]), 'gamma0s': array([3.17568078, 3.09340252, 3.09340252]), 'gamma3s': array([0.38062752, 0.3773115 , 0.3773115 ]), 'gamma4s': array([0.14023119, 0.1390095 , 0.1390095 ]), 'gammans': array([0.31284   , 0.31284   , 0.31435674, 0.31435674, 0.31435674,
        0.31435674]), 'dimer': 0.022, '_kxa': array([-2.90207898, -2.87291236, -2.84374574, -2.81457911, -2.78541249,
        -2.75624587, -2.72707925, -2.69791262, -2.668746  , -2.63957938,
        -2.61041275, -2.58124613, -2.55207951, -2.52291288, -2.49374626,
        -2.46457964, -2.43541302, -2.40624639,

In [8]:
import numpy as np

In [9]:
np.savez_compressed('test.npz', **fb.__dict__)

In [10]:
obj = FilledBands()

In [11]:
data = np.load('test.npz', allow_pickle=True)

In [12]:
for attr in data.files:
    setattr(obj, attr, data[attr].item())

In [19]:
obj.bs.K.sl.__dict__

{'eps': 0.01, 'theta': 0, 'strain': array([[ 0.01   ,  0.     ],
        [ 0.     , -0.00165]]), 'deltas': [array([0.     , 0.99835]),
  array([ 0.87468566, -0.499175  ]),
  array([-0.87468566, -0.499175  ])], 'deltans': [array([1.74937132, 0.        ]),
  array([-1.74937132,  0.        ]),
  array([0.87468566, 1.497525  ]),
  array([ 0.87468566, -1.497525  ]),
  array([-0.87468566,  1.497525  ]),
  array([-0.87468566, -1.497525  ])], 'gamma0s': [3.175680777907145,
  3.0934025208166527,
  3.0934025208166527], 'gamma3s': [0.38062751755961866,
  0.37731150457745305,
  0.37731150457745305], 'gamma4s': [0.1402311906798595,
  0.1390095016864301,
  0.1390095016864301], 'gammans': [0.31284000000000006,
  0.31284000000000006,
  0.3143567430298338,
  0.3143567430298338,
  0.3143567430298338,
  0.3143567430298338], 'dimer': 0.022, '_kxa': array([-2.90207898, -2.87291236, -2.84374574, -2.81457911, -2.78541249,
        -2.75624587, -2.72707925, -2.69791262, -2.668746  , -2.63957938,
        -2.610

# Check file size npz versus h5

In [1]:
from blg_strain.lattice import StrainedLattice
from blg_strain.bands import BandStructure, FilledBands

In [2]:
sl = StrainedLattice(0.01, 0.1)

In [3]:
bs = BandStructure(sl, Delta=0.01)
bs.calculate(500,500)

In [4]:
fb = FilledBands(bs)

In [5]:
fb.calculate()

In [6]:
%%time
fb.save('test.npz')

Wall time: 12.1 s


In [7]:
%%time
fb.save_hdf5('test.h5')

Wall time: 2.36 s


In [8]:
%%time
fb.save_hdf5('testc.h5', compression=9)

Wall time: 16.2 s


In [9]:
%%time
fb2 = FilledBands.load('test.npz')

Wall time: 2.61 s


In [12]:
%%time
fb2 = FilledBands.load_hdf5('test.h5')

Wall time: 1.77 s


In [13]:
%%time
fb2 = FilledBands.load_hdf5('testc.h5')

Wall time: 3.1 s


In [7]:
bs2 = BandStructure.load('test.npz')
# bs2 = bs.load_hdf5('test.h5')

In [19]:
fb = FilledBands.load('test.npz')
fb2 = FilledBands.load_hdf5('test.h5')

In [20]:
fb2.bs.K.__dict__

{'sl': <blg_strain.lattice.StrainedLattice at 0x1fcc0c42bc8>,
 'window': 0.1,
 'Delta': 0.01,
 'valley': 'K',
 'E': array([[[-0.56459309, -0.56405079, -0.56351008, ..., -0.56179253,
          -0.5623263 , -0.56286168],
         [-0.56396032, -0.56341662, -0.56287452, ..., -0.56114417,
          -0.56167931, -0.56221605],
         [-0.56332973, -0.56278463, -0.56224113, ..., -0.56049794,
          -0.56103444, -0.56157254],
         ...,
         [-0.59213391, -0.59136163, -0.59059081, ..., -0.58344267,
          -0.58419923, -0.58495731],
         [-0.5927328 , -0.5919611 , -0.59119086, ..., -0.58404172,
          -0.58479766, -0.58555514],
         [-0.59333276, -0.59256164, -0.59179198, ..., -0.58464185,
          -0.58539719, -0.58615406]],
 
        [[-0.20208265, -0.2014194 , -0.20075682, ..., -0.19672539,
          -0.19738853, -0.19805238],
         [-0.20161886, -0.20095544, -0.20029268, ..., -0.19625672,
          -0.19692007, -0.19758413],
         [-0.20115577, -0.20049219, 

In [42]:
import numpy as np

In [43]:
data = np.load('test.npz', allow_pickle=True)

In [44]:
bs = data['bs']

In [55]:
data['EF'].ndim

0

In [49]:
bs.K.__dict__

{'sl': <blg_strain.lattice.StrainedLattice at 0x22d0d3209c8>,
 'window': 0.1,
 'Delta': 0.01,
 'valley': 'K',
 '_kxa': array([2.36151163, 2.36201414, 2.36251665, 2.36301917, 2.36352168,
        2.36402419, 2.3645267 , 2.36502922, 2.36553173, 2.36603424,
        2.36653675, 2.36703927, 2.36754178, 2.36804429, 2.3685468 ,
        2.36904932, 2.36955183, 2.37005434, 2.37055685, 2.37105937,
        2.37156188, 2.37206439, 2.37256691, 2.37306942, 2.37357193,
        2.37407444, 2.37457696, 2.37507947, 2.37558198, 2.37608449,
        2.37658701, 2.37708952, 2.37759203, 2.37809454, 2.37859706,
        2.37909957, 2.37960208, 2.38010459, 2.38060711, 2.38110962,
        2.38161213, 2.38211464, 2.38261716, 2.38311967, 2.38362218,
        2.38412469, 2.38462721, 2.38512972, 2.38563223, 2.38613474,
        2.38663726, 2.38713977, 2.38764228, 2.38814479, 2.38864731,
        2.38914982, 2.38965233, 2.39015484, 2.39065736, 2.39115987,
        2.39166238, 2.3921649 , 2.39266741, 2.39316992, 2.39367243

# Now don't save classes shared commonly (e.g. don't save StrainedLattice multiple times)